### ISSUE TITLE
Doesn't work anymore with newer versions of gst-python

### ISSUE THREAD

**Issue by ambyjkl** [bmerry/rbtempo#2]
In newer versions of gst-python (since 1.5.2), Gst needs to be initialized with an argv array for the APIs to work. Since we don't need any arguments, the fix is to initialize Gst with an empty array as Gst.init([]) in the do_activate method.

**Comment by bmerry** [comment]
Looks like it's a gst-python bug that it doesn't realise that Rhythmbox has already initialised Gst without the Python bindings. I've filed https://bugzilla.gnome.org/show_bug.cgi?id=788088.

**Comment by bmerry** [comment]
@Ambyjkl what version of Rhythmbox are you using? I've tried with 3.4.1 in Ubuntu 17.10 beta, and 3.3 from Ubuntu 16.04, and as far as I can tell neither of them use the gst-python overrides that are causing the problem (the python-gst package isn't even installed).

**Comment by bmerry** [comment]
@Ambyjkl never mind I figured it out: installing python3-gst-1.0 changes the behaviour of using gst from Python and triggers the bug.
