### ISSUE TITLE
Please update the plugin for Flatpak.

### ISSUE THREAD

**Issue by CHJ85** [bmerry/rbtempo#4]
Can you please update this plugin for flatpak users? It only works on regular system wide installation of Rhythmbox.

**Comment by bmerry** [comment]
Sorry, I've never used Flatpak, so I don't know what would be needed or why the plugin wouldn't work with Flatpak.

**Comment by CHJ85** [comment]
Nah okay. I ended up installing Rhythmbox from the repo instead and now it works fine.
Great plugin btw. 
I listen to podcasts and audiobooks using Rhythmbox. So being able to speed up the tempo is very useful. I really think it should be included as one of the default plugins.
Do you think you could reach out to the Rhythmbox devs on Gitlab and ask them to implement it?

**Comment by bmerry** [comment]
I'm afraid it's not a plugin I'm using myself any more - you'll notice the last update was 4 years ago. You might have better luck reaching out as someone who is actually going to use it and possibly help test it etc.

**Comment by CHJ85** [comment]
Okay gotcha.
